name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
      - name: Install Poetry
        run: |
          pipx install poetry==1.8.3
          poetry config virtualenvs.create false
      - name: Install pre-commit
        run: pipx install pre-commit
      - name: Install dependencies
        run: poetry install
      - name: Run pre-commit
        run: pre-commit run -a
